families.py
opoly1d.py

Fixes #15 Inverse induced distribution divide by zero.

Fixes #15 Inverse induced distribution divide by zero

---

demos/build_pce.py
linalg_utils.py
opolynd.py
pce.py
tests/linalg.py

Cleanup for WAFP routines for parameter sampling. Major change is actual implementation of max-determinant instead of a cheap+dirty workaround.

Wafp determinant

---

indexing.py

fixes issue12 Implement more multi-index sets

---

C_eval.py
families.py
opoly1d.py
opolynd.py
quad_mod.py
tests/jacobipolys.py

It seems it's not fast as we expect based on tests I did, but it's accurate.
Need more tests and refinement for efficiency.
Modifications are added in class(families.py). There are several .py files yielding the same functionality. I can push them if needed for testing.

Fix #13 add fast algorithm for (inverse) induced sampling

---

demos/anisotropic_distribution.py
demos/build_pce.py
demos/discrete_uniform.py
distributions.py
families.py
opoly1d.py
pce.py
tests/discrete_cheb.py
transformations.py
utils/casting.py

- some bug fixes
- discrete uniform distributions
- tensorial distributions

Discrete uniform distributions + fixes

---

.github/workflows/pythonapp.yml
README.md

Update README with build badge

Basic build update

---

distributions.py
pce.py
requirements.txt
tests/test_pce.py
utils/version.py

Legacy option for random number generation allows numpy < 1.15.2.
Also fixes quantile mapping issue

Quantiles and numpy fix

---

tests/test_discrete_cheb.py
tests/test_jacobipolys.py

Tolerance loosening to address #41 build

Tolerance loosening for #41

---

UncertainSCI/indexing.py
UncertainSCI/opolynd.py
UncertainSCI/pce.py
UncertainSCI/utils/linalg.py
demos/anisotropic_distribution.py
demos/build_pce.py
demos/build_pce_exp.py
demos/build_pce_normal.py
demos/quantiles.py
tests/test_indexing.py
tests/test_linalg.py

Base functionality for:
- adaptive construction of polynomial space
- adaptive sampling upon index refinement
- budget-aware resampling
- leave one out cross validation metric
New tests in `tests` subfolder:
- `test_indexing.py`
- some Gram-Schmidt tests in `test_linalg.py`

Adaptive PCE order and cross validation

---

UncertainSCI/pce.py
demos/adapt_pce.py
tests/test_linalg.py

Demo for new adaptive procedures

Adaptive demo

---

UncertainSCI/indexing.py
UncertainSCI/opoly1d.py
UncertainSCI/opolynd.py
UncertainSCI/pce.py
UncertainSCI/transformations.py
demos/sensitivity_measures.py
tests/test_indexing.py
tests/test_pce.py
tests/test_polys.py
tests/test_quad.py

Derivative-based sensitivity.
New tests in `tests/`
- `test_pce.py`
- `test_indexing.py`
New demo `demos/sensitivity_measures.py`

Diff sensitivity

---

UncertainSCI/opolynd.py

Caused troubles when evaluating discrete chebyshev distributions

Call as keyword instead of optional argument

---

UncertainSCI/model_examples.py
docs/conf.py
docs/dev_docs/HowToTutorial.md
docs/references.bib
docs/requirements.txt
docs/tutorials/index.rst
docs/tutorials/models.md
docs/tutorials/parameters.md
docs/tutorials/template.md

I'd like some feedback on how to solve some problems I've come up against in my initial sphinx tutorials. Mainly I want to look at stuff in `docs/tutorials/models.md` and `docs/tutorials/parameters.md`. The problem is that at present Sphinx does not render things as I'd like. Here are the current issues I have on my local machine:
- making inline (in text) equations. Markdown suggests that I can write something like $x$, but that doesn't render for me. Regular equations (e.g., with `\begin{equation}`) work ok
- making tables. In `models.md` there is a table I tried to make about halfway through the source based on some things I found online, but the result is not rendered
- citations and references. For a test I've tried a test citation in `models.md` (after the table). According to the …

Initial drafts of model, parameters tutorials

---

docs/_static/css/main.css
docs/_templates/layout.html
docs/conf.py

- add custom css file 
- change accent color of nav sidebar
- adjust body font

Exploration of RTD Customization

---

.gitignore
demos/basic_uq_example.py

added the simple demo file. Some of the comments make references to other examples which need updated

adding simple demo

---

README.md
paper/paper.bib

changes requested by @whedon during the review:
(https://github.com/openjournals/joss-reviews/issues/4094)

Joss corrections

---

UncertainSCI/distributions.py

Fixed boolean comparisons

---

UncertainSCI/distributions.py

Fix for Gamma distribution construction error

Affine map + sample construction

---

UncertainSCI/distributions.py

Fixes scaling issues associated with sampling Gamma Distributions wrt the parameter `k`

Fixed scaling issue

---

.github/workflows/pythonapp.yml
demos/build_pce_exp.py

adding pytests to github actions
